version: '3'

services:
  nodejs_portfolio:
    entrypoint: "/bin/sh ./docker-entrypoint.sh"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/application
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.portfolio.rule=Host(`${DOMAIN}`)
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portfolio.tls.certresolver=lets_encrypt_resolver"
    expose:
      - 8101
    networks:
      proxy:
        ipv4_address: 10.200.0.51

networks:
  proxy:
    external: true
